modify install and run to handle double click

diff --git a/video-player/install-player b/video-player/install-player
--- a/video-player/install-player
+++ b/video-player/install-player
@@ -9,32 +9,41 @@ RED='\033[0;31m'
 GREEN='\033[0;32m'
 NC='\033[0m' # No Color
 
+# abb 20201026, to run from double click
+DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+echo -e "Running run from $DIR"
+cd "${DIR}"
+
 if [ $(id -u) = 0 ]; then
    echo "Do not run with sudo. Try again without sudo"
    exit 1
 fi
 
-if ! type "virtualenv" > /dev/null; then
-	echo '==='
-	echo "=== install-player: Installing virtualenv"
-	echo '==='
-	#sudo /usr/bin/easy_install virtualenv
-	#pip install virtualenv
-	#sudo apt-get -qy install python-virtualenv
-	pip install virtualenv
-fi
+# abb removed 20201026
+#if ! type "virtualenv" > /dev/null; then
+#	echo '==='
+#	echo "=== install-player: Installing virtualenv"
+#	echo '==='
+#	#sudo /usr/bin/easy_install virtualenv
+#	#pip install virtualenv
+#	#sudo apt-get -qy install python-virtualenv
+#	pip install virtualenv
+#fi
 
 if [ ! -d "player_env/" ]; then
 	echo '==='
 	echo "=== install-player: Making Python 3 virtual environment in $PWD/player_env"
 	echo '==='
-	if ! type "virtualenv" > /dev/null; then
-		echo -e 'install-player: ${RED}ERROR${NC}: DID NOT INSTALL VIRTUALENV -->> ABORTING'
-		exit 0
-	else
-		mkdir player_env
-		virtualenv -p python3 --no-site-packages player_env
-	fi
+	# abb removed 20201026
+	#if ! type "virtualenv" > /dev/null; then
+	#	echo -e 'install-player: ${RED}ERROR${NC}: DID NOT INSTALL VIRTUALENV -->> ABORTING'
+	#	exit 0
+	#else
+		# abb 20201026
+		#mkdir player_env
+		#virtualenv -p python3 --no-site-packages player_env
+		python3 -m venv player_env
+	#fi
 else
 	echo '==='
 	echo "=== install-player: Python 3 virtual environment already exists in $PWD/player_env"
@@ -68,3 +77,5 @@ deactivate
 # done
 echo -e "${GREEN}Success${NC}: The video-player is installed."
 echo "Run the video-player with './player'"
+
+exec /bin/bash
